site_name: Oscilla Labs
site_url: https://oscillalabs.com
site_description: Zaman Serilerinde Çok Ölçekli Geometrik Analiz

theme:
  name: material
  custom_dir: overrides
  language: tr
  palette:
    # Karanlık ve Aydınlık Mod Geçişi
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Karanlık Moda Geç
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Aydınlık Moda Geç

  features:
    - navigation.tabs              # Üst menü
    - navigation.tabs.sticky       # Kaydırınca sabit kalan menü
    - navigation.sections          # Yan menüde gruplandırma
    - navigation.expand            # Menüleri otomatik aç
    - navigation.top               # "Yukarı Çık" butonu
    - navigation.indexes           # Klasör isimlerine tıklanabilirlik
    - search.suggest               # Akıllı arama önerileri
    - search.highlight             # Arama sonuçlarını boyama
    - content.code.copy            # Kod bloklarına "Kopyala" butonu

markdown_extensions:
  - admonition                     # Bilgi kutucukları (Note, Warning vb.)
  - pymdownx.details               # Açılır kapanır paneller
  - pymdownx.tabbed:               # Sekmeli içerik (Örn: Python/Java kodu yan yana)
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - stylesheets/extra.css          # Özel stil dokunuşları için